views:
  - output: "{{qid}}.html"
    query: "churches.rq"
    template: "pages/church.html"
  - output: "map.json"
    query: "churches.rq"
    template: "pages/map.json"
  - output: "style.html"
    query: "styles.rq"
    template: "pages/style.html"
  - output: "sitemap.xml"
    query: "churches.rq"
    template: "pages/sitemap.xml"
  - output: "material.html"
    query: "materials-list.rq"
    template: "pages/material.html"

  - output: "404.html"
    template: "static/404.html"
  - output: "about.html"
    template: "static/about.html"
  - output: "index.html"
    template: "static/index.html"
  - output: "map.html"
    template: "static/map.html"